AWSTemplateFormatVersion: '2010-09-09'
Description: AWS::DynamoDB::Table - core-automation-api-app - resources

Parameters:
  Scope:
    Type: String
    Default: ''
    AllowedPattern: '^([a-z]+-)*$'

  Client:
    Type: String
    Default: "core"
    AllowedPattern: "^[a-z]+$"

  Portfolio:
    Type: String
    Default: "core"

  App:
    Type: String
    Default: "facts-db"

  Branch:
    Type: String
    Default: "master"

  Build:
    Type: String

  Environment:
    Type: String
    Default: "prod"

  PortfoliosTableName:
    Type: String
    Default: core-automation-portfolios

  AppsTableName:
    Type: String
    Default: core-automation-apps

  ZonesTableName:
    Type: String
    Default: core-automation-zones

Resources:
  DummyResource:
    Type: AWS::CloudFormation::WaitConditionHandle
    Metadata:
      Build:
        Ref: Build

  ChangePortfoliosLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "/aws/lambda/${Scope}core-automation-change-portfolios-lambda"
      RetentionInDays: 1
      Tags:
        - Key: Name
          Value: !Sub "${Scope}core-automation-change-events-portfolios-lambda"
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  ChangeAppsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Scope}core-automation-change-apps-lambda"
      RetentionInDays: 1
      Tags:
        - Key: Name
          Value: !Sub "${Scope}core-automation-change-events-apps-lambda"
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  ChangeZonesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "/aws/lambda/${Scope}core-automation-change-zones-lambda"
      RetentionInDays: 1
      Tags:
        - Key: Name
          Value: !Sub "${Scope}core-automation-change-events-zones-lambda"
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    DependsOn:
      - ChangePortfoliosLogGroup
      - ChangeAppsLogGroup
      - ChangeZonesLogGroup
    Properties:
      RoleName:
        Fn::Sub: "${Scope}CoreAutomationFactsLambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBStreamPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:DeleteItem
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:DescribeStream
                  - dynamodb:ListStreams
                Resource:
                  - Fn::GetAtt:
                      - PortfoliosTable
                      - Arn
                  - Fn::GetAtt:
                      - AppsTable
                      - Arn
                  - Fn::GetAtt:
                      - ZonesTable
                      - Arn
                  - Fn::GetAtt:
                      - PortfoliosTable
                      - StreamArn
                  - Fn::GetAtt:
                      - AppsTable
                      - StreamArn
                  - Fn::GetAtt:
                      - ZonesTable
                      - StreamArn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - Fn::Sub: 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${Scope}core-automation-change-portfolios-lambda:*'
                  - Fn::Sub: 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${Scope}core-automation-change-apps-lambda:*'
                  - Fn::Sub: 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${Scope}core-automation-change-zones-lambda:*'
      Path: /
      Tags:
        - Key: Name
          Value: !Sub "${Scope}CoreAutomationFactsLambdaExecutionRole"
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  ChangePortfoliosLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaExecutionRole
      - ChangePortfoliosLogGroup
    Properties:
      FunctionName: !Sub "${Scope}core-automation-change-portfolios-lambda"
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Code:
        ZipFile: |
         {{ read_file("portfolio_lambda.py") | indent(12) }}
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          PORTFOLIOS_TABLE:
            Ref: PortfoliosTableName
          APPS_TABLE:
            Ref: AppsTableName
          ZONES_TABLE:
            Ref: ZonesTableName
          LOG_LEVEL: INFO
      LoggingConfig:
        LogGroup: !Sub "/aws/lambda/${Scope}core-automation-change-portfolios-lambda"
      Tags:
        - Key: Name
          Value: !Sub "${Scope}core-automation-change-portfolios-lambda"
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  ChangeAppsLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaExecutionRole
      - ChangeAppsLogGroup
    Properties:
      FunctionName: !Sub "${Scope}core-automation-change-apps-lambda"
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Code:
        ZipFile: |
          {{ read_file("apps_lambda.py") | indent(12) }}
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          APPS_TABLE:
            Ref: AppsTableName
          LOG_LEVEL: INFO
      LoggingConfig:
        LogGroup: !Sub "/aws/lambda/${Scope}core-automation-change-apps-lambda"
      Tags:
        - Key: Name
          Value: !Sub "${Scope}core-automation-change-apps-lambda"
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  ChangeZonesLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaExecutionRole
      - ChangeZonesLogGroup
    Properties:
      FunctionName: !Sub "${Scope}core-automation-change-zones-lambda"
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Runtime: python3.12
      Code:
        ZipFile: |
          {{ read_file("zones_lambda.py") | indent(12) }}
      Timeout: 30
      Environment:
        Variables:
          ZONES_TABLE:
            Ref: ZonesTableName
          LOG_LEVEL: INFO
      LoggingConfig:
        LogGroup: !Sub "/aws/lambda/${Scope}core-automation-change-zones-lambda"
      Tags:
        - Key: Name
          Value: !Sub "${Scope}core-automation-change-zones-lambda"
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  PortfoliosTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 100
      EventSourceArn:
        Fn::GetAtt:
          - PortfoliosTable
          - StreamArn
      FunctionName:
        Fn::GetAtt:
          - ChangePortfoliosLambda
          - Arn
      StartingPosition: LATEST

  AppsTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 100
      EventSourceArn:
        Fn::GetAtt:
          - AppsTable
          - StreamArn
      FunctionName:
        Fn::GetAtt:
          - ChangeAppsLambda
          - Arn
      StartingPosition: LATEST

  ZonesTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 100
      EventSourceArn:
        Fn::GetAtt:
          - ZonesTable
          - StreamArn
      FunctionName:
        Fn::GetAtt:
          - ChangeZonesLambda
          - Arn
      StartingPosition: LATEST

  PortfoliosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Portfolio
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Portfolio
          KeyType: HASH
      TableName:
        Ref: PortfoliosTableName
      StreamSpecification:
        StreamViewType: OLD_IMAGE
      GlobalSecondaryIndexes: []
      Tags:
        - Key: Name
          Value: !Ref PortfoliosTableName
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  ZonesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ClientPortfolio
          AttributeType: S
        - AttributeName: Zone
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ClientPortfolio
          KeyType: HASH
        - AttributeName: Zone
          KeyType: RANGE
      TableName:
        Ref: ZonesTableName
      StreamSpecification:
        StreamViewType: OLD_IMAGE
      GlobalSecondaryIndexes: []
      Tags:
        - Key: Name
          Value: !Ref ZonesTableName
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

  AppsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ClientPortfolio
          AttributeType: S
        - AttributeName: AppRegex
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ClientPortfolio
          KeyType: HASH
        - AttributeName: AppRegex
          KeyType: RANGE
      TableName:
        Ref: AppsTableName
      StreamSpecification:
        StreamViewType: OLD_IMAGE
      GlobalSecondaryIndexes: []
      Tags:
        - Key: Name
          Value: !Ref AppsTableName
        - Key: Scope
          Value: !Ref Scope
        - Key: Client
          Value: !Ref Client
        - Key: Environment
          Value: !Ref Environment
        - Key: Portfolio
          Value: !Ref Portfolio
        - Key: App
          Value: !Ref App
        - Key: Branch
          Value: !Ref Branch
        - Key: Build
          Value: !Ref Build

Outputs:
  
  PortfoliosTableArn:
    Value:
      Fn::GetAtt:
        - PortfoliosTable
        - Arn
    Export:
      Name: !Sub "${Scope}CoreAutomationPortfoliosTableArn"

  PortfoliosTableName:
    Value:
      Ref: PortfoliosTableName
    Export:
      Name: !Sub "${Scope}CoreAutomationPortfoliosTableName"

  ZonesTableArn:
    Value:
      Fn::GetAtt:
        - ZonesTable
        - Arn
    Export:
      Name: !Sub "${Scope}CoreAutomationZonesTableArn"

  ZonesTableName:
    Value:
      Ref: ZonesTableName
    Export:
      Name: !Sub "${Scope}CoreAutomationZonesTableName"

  AppsTableArn:
    Value:
      Fn::GetAtt:
        - AppsTable
        - Arn
    Export:
      Name: !Sub "${Scope}CoreAutomationAppsTableArn"

  AppsTableName:
    Value:
      Ref: AppsTableName
    Export:
      Name: !Sub "${Scope}CoreAutomationAppsTableName"
